apiVersion: v1
kind: Service
metadata:
  name: prometheus-adapter
  namespace: hausa-voice-swarm
  labels:
    app: prometheus-adapter
    app.kubernetes.io/part-of: hausa-voice-swarm
spec:
  type: ClusterIP
  selector:
    app: prometheus-adapter
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
